export const CREATE_PASSENGER_SUCCESS = "CREATE_PASSENGER_SUCCESS";
export const UPDATE_PASSENGER_SUCCESS = "UPDATE_PASSENGER_SUCCESS";
export const LOAD_PASSENGER_SUCCESS = "LOAD_PASSENGER_SUCCESS";
export const DELETE_PASSENGER_SUCCESS = "DELETE_PASSENGER_SUCCESS";
export const SHOW_PASSENGERS_BY_FLIGHT_ID = "SHOW_PASSENGERS_BY_FLIGHT_ID";

export const FILTER_BY_CHECKIN = "FILTER_BY_CHECKIN";
export const FILTER_BY_WHEELCHAIR = "FILTER_BY_WHEELCHAIR";
export const FILTER_BY_INFANT = "FILTER_BY_INFANT";
export const CLEAR_FILTER = "CLEAR_FILTER";

export const FILTER_BY_PASSPORT = "FILTER_BY_PASSPORT";
export const FILTER_BY_ADDRESS = "FILTER_BY_ADDRESS";
export const FILTER_BY_DOB = "FILTER_BY_DOB";

export const CREATE_FLIGHT_SUCCESS = "CREATE_FLIGHT_SUCCESS";
export const UPDATE_FLIGHT_SUCCESS = "UPDATE_FLIGHT_SUCCESS";
export const LOAD_FLIGHT_SUCCESS = "LOAD_FLIGHT_SUCCESS";
export const FILTER_RESERVED_SEATS_BY_ID = "FILTER_RESERVED_SEATS_BY_ID";

export const UPDATE_SEAT_SUCCESS = "UPDATE_SEAT_SUCCESS";
export const UPDATE_MEAL_SUCCESS = "UPDATE_MEAL_SUCCESS";

export const LOAD_SERVICES_SUCCESS = "LOAD_SERVICES_SUCCESS";
export const CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS";
export const UPDATE_SERVICE_SUCCESS = "UPDATE_SERVICE_SUCCESS";
export const DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS";

export const SEARCH_FLIGHT_BY_DEPARTURE = "SEARCH_FLIGHT_BY_DEPARTURE";
